# Generated by Django 4.2.11 on 2024-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_client', models.IntegerField(default=0)),
                ('num_cde', models.IntegerField(default=0)),
                ('num_ligne', models.IntegerField(default=0)),
                ('date_depart', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('ferme_prev', models.CharField(max_length=1)),
                ('ref_commande', models.CharField(max_length=128)),
                ('num_appel', models.CharField(max_length=128)),
                ('poste', models.IntegerField(default=0)),
                ('produit', models.IntegerField(default=0)),
                ('ref_interne', models.CharField(max_length=128)),
                ('nom_produit', models.CharField(max_length=128)),
                ('quantite_cde', models.IntegerField(default=0)),
                ('prix_vente', models.FloatField(default=0.0)),
                ('num_unique', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=128)),
                ('stock', models.IntegerField(default=0)),
                ('emplacement', models.CharField(max_length=20)),
                ('stock_recalcule', models.IntegerField(default=0)),
            ],
        ),
    ]
