# Generated by Django 4.2.11 on 2024-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='nom_client',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
