# Generated by Django 4.2.11 on 2024-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0002_portefeuille_nom_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portefeuille',
            name='date_arrivee',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='date_depart',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='ferme_prev',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='nom_client',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='nom_produit',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='num_appel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='num_cde',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='num_client',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='num_ligne',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='num_unique',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='poste',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='prix_vente',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='produit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='quantite_cde',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='ref_commande',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='ref_interne',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nom',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_recalcule',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
