# Generated by Django 4.2.11 on 2024-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0003_alter_portefeuille_date_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='montant_total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
