# Generated by Django 4.2.11 on 2024-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0004_portefeuille_montant_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of', models.IntegerField(blank=True, default=0)),
                ('num_produit', models.IntegerField(blank=True, default=0)),
                ('num_lancement', models.CharField(blank=True, max_length=15)),
                ('statut_of', models.CharField(blank=True, max_length=5)),
                ('date_debut', models.DateField(blank=True)),
                ('date_fin', models.DateField(blank=True)),
                ('quantite', models.IntegerField(blank=True, default=0)),
                ('id_cde', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
