# Generated by Django 4.2.11 on 2024-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0005_baseof'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_operation', models.IntegerField(blank=True, default=0)),
                ('num_phase_operation', models.CharField(blank=True, max_length=5)),
                ('num_operation', models.IntegerField(blank=True, default=0)),
                ('phase', models.CharField(blank=True, max_length=10)),
                ('atelier', models.CharField(blank=True, max_length=10)),
                ('machine', models.CharField(blank=True, max_length=10)),
                ('description_operation', models.CharField(blank=True, max_length=50)),
                ('temps_prepa', models.FloatField(blank=True, default=0.0)),
                ('temps_prod', models.FloatField(blank=True, default=0.0)),
                ('temps_total', models.FloatField(blank=True, default=0.0)),
                ('date_fab', models.DateField(blank=True)),
                ('solder', models.BooleanField()),
                ('num_unique', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
