# Generated by Django 4.2.11 on 2024-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0006_baseoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_nomenclature', models.IntegerField(blank=True, default=0)),
                ('num_phase_nomenclature', models.CharField(blank=True, max_length=5)),
                ('num_produit', models.IntegerField(blank=True, default=0)),
                ('quantite_besoin', models.FloatField(blank=True, default=0.0)),
                ('besoin_solder', models.BooleanField()),
                ('designation_produit', models.CharField(blank=True, max_length=50)),
                ('date_conso', models.DateField(blank=True)),
                ('num_unique_nomenclature', models.CharField(blank=True, max_length=50)),
                ('produit_gp', models.BooleanField()),
            ],
        ),
    ]
