# Generated by Django 4.2.11 on 2024-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0007_basenomenclature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_global', models.IntegerField(blank=True, default=0)),
                ('nom_produit_stock', models.CharField(blank=True, max_length=128)),
                ('stock_global', models.FloatField(blank=True, default=0.0)),
                ('stock_recalcule_global', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
