# Generated by Django 4.2.11 on 2024-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0008_stockgobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseof',
            name='nbre_operation',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
