# Generated by Django 4.2.11 on 2024-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0009_baseof_nbre_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(blank=True, max_length=80)),
                ('num_commande', models.IntegerField(blank=True, default=0)),
                ('num_produit_achat', models.IntegerField(blank=True, default=0)),
                ('date_liv_accorde', models.DateField(blank=True)),
                ('num_ligne', models.IntegerField(blank=True, default=0)),
                ('quantite_commande', models.FloatField(blank=True, default=0.0)),
                ('reception', models.BooleanField()),
                ('reference_cde', models.CharField(blank=True, max_length=125)),
            ],
        ),
    ]
