# Generated by Django 4.2.11 on 2024-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0010_commandefournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseof',
            name='qte_base',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
