# Generated by Django 4.2.11 on 2024-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0011_baseof_qte_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseof',
            old_name='id_cde',
            new_name='sem_contrainte',
        ),
        migrations.AddField(
            model_name='baseof',
            name='contrainte',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='das',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
