# Generated by Django 4.2.11 on 2025-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0012_rename_id_cde_baseof_sem_contrainte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenomenclature',
            name='famille_produit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='num_fournisseur',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
